server:
  port: 8082

spring:
  application:
    name: service-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oidc_op?
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        port: 9999 #控制台交流端口
        dashboard: 127.0.0.1:8080 #控制台地址

#开启驼峰映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true
